### ISSUE TITLE
Описать требования к системе

### ISSUE THREAD

**Issue by rozavetrov** [kaverhovsky/todo-list-app#1]
Необходимо сформировать MVP приложения. Для этого на первом этапе нужно описать требования к функционалу системы.

**Comment by kaverhovsky** [comment]
# Требования к  mvp приложения TODO 
Здесь будут описаны различные требования к приложению todo-list-app. Требования касаются MVP,  то есть минимального жизнеспособного продукта, который будет покрывать потребности пользователя. Тут не будет killer-фич, выделяющих наш продукт от подобных ему. Только core без мишуры.

Без чего не может обойтись человек, желающий описать и систематизировать задачи, которые он держит у себя в голове?
 Главное: 
1. Возможность оперировать задачами.  Создание, удаление, обновление и т.п.
2. Возможность группировать задачи.

Это основные моменты, отражающие работу с артефактами внутри системы. Хотелки, которые плавно перетекают в функциональные требования, но о них немного позже.

## Предметная область
Чтобы четко понимать, о чем мы говорим при описании требований, необходимо обозначить состав предметной области.
Сущности:
**Пользователь (User)** - непосредственно пользователь, работающий внутри приложения. 
**Задача (Task)**  - задача, главная сущность в системе. 
**Список задач (List)** - список задач, позволяющий группировать задачи.

##  Функциональные требования
Система должна предоставлять следующие функциональности:

Пользователь (личный кабинет):
- Регистрироваться (создание личного кабинета)
 -- Удалять личный кабинет со всеми связанными с ним объектами --
 -- Изменять имя, логин и пароль --

Задачи:
- Создавать, удалять задачи
- Закрывать и открывать задачи (нажатием на чекбокс)
- Оперировать шагами:
	- Добавлять и удалять шаги
	- Изменять имя шага
	- Менять порядок шагов
- Редактировать описание задачи (обычное текстовое поле)
 -- Указывать дедлайн задачи и отображать оставшееся время и факт "протухания" задачи --

Списки:
- Создавать и удалять список
- Изменять состав списка:
	- Добавлять задачу в список
	- Удалять задачу из списка
	- Менять порядок задач

**Comment by kaverhovsky** [comment]
Core описал, в дальнейшем намечу улучшения, которые можно будет реализовать сразу после mvp

**Comment by kaverhovsky** [comment]
## features
Функциональные:
- Поиск по названию задач / поиск по всему контенту задачи
- Повторяющиеся задачи, т.е. периодическая настриваемая генерация задач (например, ежедневный список дел)
- Шаблонизация для повторящихся задач
- Механизм напоминаний с уведомлениями
- Настройки в личном кабинете (уведомления, внешний вид и т.д.)
- Тегирование задач, поддержка настройки тегов
- Совместная работа - тут поподробнее:
	- Четко очерченное рабочее пространство (заметки, списки, теги), которое можно расшарить с другими пользователями
	- Совместное одновременное редактирование
	- Система контроля доступа (?)
- Загрузка файлов (?)
- Сортировка задач в списке
- 

Нефункциональные (в основном касается фронта):
- Общее требование - минимальное число шагов для выполнения пользовательского действия, более user-friendly исполнение
- Дефолтные списки задач (my day, important и т.д.)
- Шорткаты в интерфейсе (например, нажатие на звездочку для пометки задачи как "important")
- Настраиваемые темы
- Обучение (?)
- Premium подписка ( :D )
- Разные view задач в интерфейсе (список, таблица, плитка и т.п.)
